---
services:
  postgres:
    image: postgres:17.0-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    depends_on:
      - postgres
    networks:
      - app_network
  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    depends_on:
      - postgres
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    command:
      - redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
