---
name: lint-and-build
on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install shap
        run: yarn add sharp
      - name: lint test
        run: yarn lint
      - name: build test app
        run: yarn build
